# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'

  # Pods for FinalChallenge

  target 'FinalChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinalChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
